Fix release-mode build with MSVC
Fixes:
```
protocol\whist\debug\debug_console.cpp(98): error C2220: the following warning is treated as an error
protocol\whist\debug\debug_console.cpp(98): warning C4551: function call missing argument list
protocol\whist\debug\debug_console.cpp(99): warning C4551: function call missing argument list
protocol\whist\debug\debug_console.cpp(100): warning C4551: function call missing argument list
protocol\whist\debug\debug_console.cpp(113): warning C4505: 'init_overrided_values': unreferenced function with internal linkage has been removed
protocol\whist\debug\debug_console.cpp(226): warning C4505: 'debug_console_thread': unreferenced function with internal linkage has been removed
protocol\whist\debug\debug_console.cpp(286): warning C4505: 'create_local_udp_listen_socket': unreferenced function with internal linkage has been removed
```