Set open() permissions argument on Windows (#5033)
If this isn't set, you end up with a file which can't be overwritten.
This caused a problem when running the protocol tests on Windows
repeatedly, because the stdout-capturing tests need to reopen the same
output file:

[----------] 7 tests from CaptureStdoutTest
[ RUN      ] CaptureStdoutTest.ClientParseArgsEmpty
C:\Users\mrt\whist\test\protocol\test\protocol_test.cpp(85): error: Expected: (fd) >= (0), actual: -1 vs 0
minkernel\crts\ucrt\src\appcrt\lowio\dup2.cpp(72) : Assertion failed: (source_fh >= 0 && (unsigned)source_fh < (unsigned)_nhandle)

(This didn't appear in CI because it does a clean build.)